### PR TITLE
Asthma SOAP

### PR DESCRIPTION
**Pull request by DrewCypher**
Test Assignment #1

### CODE REVIEW

**Comment by tangollama** [comment]
@DrewCypher congrats on getting a PR submitted. A few issues:
1. The file naming convention is wrong. The README references that files should be named - not by the common diagnosis name - but by the ICD-10 code.
2. Formatting: the format doesn't really match the markdown for format of the example. Look there and circle back with me and ask questions.
3. Utility of this exact PR: we already have an Asthma SOAP notes. Why?

Look into these and then circle back with me if needed.

**Comment by DrewCypher** [comment]
Issue #1

**Comment by DrewCypher** [comment]
Having trouble with Objective and Assessment.  Not sure why they're showing up indented.  I based the title off the title of the example (2016-ICD-CM.example.md), simply replacing example with the code.

**Comment by tangollama** [comment]
@DrewCypher, the file has HTML tags like H1's in the markup vs. the markdown format. For instance, the Objective section shouldn't be:

`<h1>Objective</h1>
`

instead, it should be:

`# Objective`

Does that make sense?

**Comment by DrewCypher** [comment]
You can see my updates above^.  Still indents even with the different formatting.

**Pull request merged**
